name: halator
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ase=3.22.1
  - babel=2.14.0
  - ipykernel=6.29.3
  - ipython=8.22.1
  - ipywidgets=7.8.0
  - libxml2=2.12.6
  - lightgbm=4.1.0
  - joblib=1.2.0
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - notebook=7.1.2
  - numpy=1.26.2
  - openbabel=3.1.1
  - openssl=3.2.1
  - optuna=3.5.0
  - pandas=2.1.1
  - pillow=10.0.1
  - pip=23.3.1
  - py3dmol=2.1.0
  - python=3.10.13
  - python_abi=3.10
  - rdkit=2023.09.3
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - submitit=1.5.1
  - xtb=6.6.1

